### ISSUE TITLE
Crashes my device

### ISSUE THREAD

**Issue by flyjet6** [openzfsonwindows/ZFSin#352] opened 2024-04-26 17:58 UTC
When installing this on windows 10 pro, after restarting windows would not boot. Only fixed by reinstalling windows. But the newer openzfs worked.

**Comment by lundman** [comment] 2024-04-26 23:01
Sorry that happened, but it is worth pointing out, it is easy to remove the driver even if it doesn't boot anymore. You don't need to re-install Windows.

https://openzfsonosx.org/wiki/Windows_bootloop

**Comment by flyjet6** [comment] 2024-04-26 23:03
How would I remove the driver when I can't boot my computer? It would enter winre

**Comment by lundman** [comment] 2024-04-26 23:06
If it fails to boot twice in a row, it enter the recovery console - or you can boot install media/rescue media to enter recovery console. Then you can delete driver.

**Comment by dooann** [comment] 2024-07-23 03:05
I have a looping issue on my Windows 11 system. I can log in, but the system gets stuck in an infinite loop during shutdown or reboot after installing this application, even after I have deleted the OpenZfs.sys file.

**Comment by sskras** [comment] 2024-07-23 07:21
@dooann, can you give more details about the loop (eg. screenshot, video clip) ?

Just in case, maybe it's be worth disabling the _"Automatic Restart"_ via _"Startup Settings"_:
[How to Disable Automatic Restart in Windows 11: A Step-by-Step Guide](https://www.supportyourtech.com/articles/how-to-disable-automatic-restart-in-windows-11-a-step-by-step-guide/#:~:text=Step%205%3A%20Navigate%20to%20%E2%80%98Troubleshoot%E2%80%99%20%3E%20%E2%80%98Advanced%20Options%E2%80%99%20%3E%20%E2%80%98Startup%20Settings%E2%80%99)

**Comment by dooann** [comment] 2024-07-25 09:52
I found that the cause of my issue is hardware-related. Thank you guys for your help.

**Comment by sskras** [comment] 2024-07-25 12:06
@flyjet6 commented [on Apr 26](https://github.com/openzfsonwindows/ZFSin/issues/352#issue-2266260146):

> When installing this on windows 10 pro, after restarting windows would not boot. Only fixed by reinstalling windows. But the newer openzfs worked.

What do you mean by "newer openzfs worked", please?

**Comment by sskras** [comment] 2024-07-25 13:25
Ah, thank you! Development of `ZFSin` is dormant for 2y already, I think.

Do you still have issue with booting with / uninstalling the `ZFSin` variant ?

**Comment by flyjet6** [comment] 2024-07-25 13:29
I didn't try installing the ZFSin variant again

**Comment by sskras** [comment] 2024-07-25 13:30
So the your original issue is fixed. I wonder of this GitHub issues should be closed as well.

(given no development ongoing anymore)

**Comment by flyjet6** [comment] 2024-07-25 13:30
Forgot to close it mb

**Closed** 2024-07-25 13:30 UTC
